// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface AddUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.User user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.User user = 1;</code>
   * @return The user.
   */
  via.sep3.dataserver.grpc.User getUser();
  /**
   * <code>.User user = 1;</code>
   */
  via.sep3.dataserver.grpc.UserOrBuilder getUserOrBuilder();
}
