// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface CourseProgressUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CourseProgressUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>int32 course_id = 2;</code>
   * @return The courseId.
   */
  int getCourseId();

  /**
   * <code>int32 current_step = 3;</code>
   * @return The currentStep.
   */
  int getCurrentStep();
}
