// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public final class DataProtocol {
  private DataProtocol() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      DataProtocol.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCoursesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetCoursesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCoursesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetCoursesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Course_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Course_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddCourseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddCourseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddCourseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddCourseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUsersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetUsersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUsersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetUsersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Role_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Role_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetLearningStepRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetLearningStepRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetLearningStepResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetLearningStepResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LearningStep_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LearningStep_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CourseDraft_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CourseDraft_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddDraftRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddDraftRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddDraftResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddDraftResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDraftRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetDraftRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDraftResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetDraftResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateLearningStepRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateLearningStepRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateLearningStepResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateLearningStepResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateDraftRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateDraftRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateDraftResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateDraftResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDraftsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetDraftsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDraftsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetDraftsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023data_protocol.proto\"\023\n\021GetCoursesReque" +
      "st\".\n\022GetCoursesResponse\022\030\n\007courses\030\001 \003(" +
      "\0132\007.Course\"\\\n\006Course\022\n\n\002id\030\001 \001(\005\022\r\n\005titl" +
      "e\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\020\n\010language" +
      "\030\004 \001(\t\022\020\n\010category\030\005 \001(\t\"Z\n\020AddCourseReq" +
      "uest\022\r\n\005title\030\001 \001(\t\022\023\n\013description\030\002 \001(\t" +
      "\022\020\n\010language\030\003 \001(\t\022\020\n\010category\030\004 \001(\t\",\n\021" +
      "AddCourseResponse\022\027\n\006course\030\001 \001(\0132\007.Cour" +
      "se\"\021\n\017GetUsersRequest\"(\n\020GetUsersRespons" +
      "e\022\024\n\005users\030\001 \003(\0132\005.User\"L\n\004User\022\n\n\002id\030\001 " +
      "\001(\005\022\020\n\010username\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022" +
      "\024\n\005roles\030\004 \003(\0132\005.Role\"\024\n\004Role\022\014\n\004role\030\001 " +
      "\001(\t\"C\n\016AddUserRequest\022\020\n\010username\030\001 \001(\t\022" +
      "\020\n\010password\030\002 \001(\t\022\r\n\005roles\030\003 \003(\t\"&\n\017AddU" +
      "serResponse\022\023\n\004user\030\001 \001(\0132\005.User\"@\n\026GetL" +
      "earningStepRequest\022\021\n\tcourse_id\030\001 \001(\005\022\023\n" +
      "\013step_number\030\002 \001(\005\"?\n\027GetLearningStepRes" +
      "ponse\022$\n\rlearning_step\030\001 \001(\0132\r.LearningS" +
      "tep\"T\n\014LearningStep\022\021\n\tcourse_id\030\001 \001(\005\022\022" +
      "\n\nstep_order\030\002 \001(\005\022\017\n\007content\030\003 \001(\t\022\014\n\004t" +
      "ype\030\004 \001(\t\"\213\001\n\013CourseDraft\022\n\n\002id\030\001 \001(\005\022\020\n" +
      "\010language\030\002 \001(\t\022\r\n\005title\030\003 \001(\t\022\023\n\013descri" +
      "ption\030\004 \001(\t\022\022\n\nteacher_id\030\005 \001(\005\022\021\n\tcours" +
      "e_id\030\006 \001(\005\022\023\n\013approved_by\030\007 \001(\005\"[\n\017AddDr" +
      "aftRequest\022\020\n\010language\030\001 \001(\t\022\r\n\005title\030\002 " +
      "\001(\t\022\023\n\013description\030\003 \001(\t\022\022\n\nteacher_id\030\004" +
      " \001(\005\"5\n\020AddDraftResponse\022!\n\013courseDraft\030" +
      "\001 \001(\0132\014.CourseDraft\"\"\n\017GetDraftRequest\022\017" +
      "\n\007draftId\030\001 \001(\005\"5\n\020GetDraftResponse\022!\n\013c" +
      "ourseDraft\030\001 \001(\0132\014.CourseDraft\"A\n\031Update" +
      "LearningStepRequest\022$\n\rlearning_step\030\001 \001" +
      "(\0132\r.LearningStep\"B\n\032UpdateLearningStepR" +
      "esponse\022$\n\rlearning_step\030\001 \001(\0132\r.Learnin" +
      "gStep\"7\n\022UpdateDraftRequest\022!\n\013courseDra" +
      "ft\030\001 \001(\0132\014.CourseDraft\"8\n\023UpdateDraftRes" +
      "ponse\022!\n\013courseDraft\030\001 \001(\0132\014.CourseDraft" +
      "\"\022\n\020GetDraftsRequest\"1\n\021GetDraftsRespons" +
      "e\022\034\n\006drafts\030\001 \003(\0132\014.CourseDraft2\305\004\n\024Data" +
      "RetrievalService\022/\n\010GetUsers\022\020.GetUsersR" +
      "equest\032\021.GetUsersResponse\022,\n\007AddUser\022\017.A" +
      "ddUserRequest\032\020.AddUserResponse\0225\n\nGetCo" +
      "urses\022\022.GetCoursesRequest\032\023.GetCoursesRe" +
      "sponse\0222\n\tAddCourse\022\021.AddCourseRequest\032\022" +
      ".AddCourseResponse\022D\n\017GetLearningStep\022\027." +
      "GetLearningStepRequest\032\030.GetLearningStep" +
      "Response\022/\n\010AddDraft\022\020.AddDraftRequest\032\021" +
      ".AddDraftResponse\022/\n\010GetDraft\022\020.GetDraft" +
      "Request\032\021.GetDraftResponse\0228\n\013UpdateDraf" +
      "t\022\023.UpdateDraftRequest\032\024.UpdateDraftResp" +
      "onse\022M\n\022UpdateLearningStep\022\032.UpdateLearn" +
      "ingStepRequest\032\033.UpdateLearningStepRespo" +
      "nse\0222\n\tGetDrafts\022\021.GetDraftsRequest\032\022.Ge" +
      "tDraftsResponseB7\n\030via.sep3.dataserver.g" +
      "rpcP\001\252\002\030via.sep3.dataserver.grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetCoursesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetCoursesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetCoursesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetCoursesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetCoursesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetCoursesResponse_descriptor,
        new java.lang.String[] { "Courses", });
    internal_static_Course_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Course_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Course_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "Language", "Category", });
    internal_static_AddCourseRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AddCourseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddCourseRequest_descriptor,
        new java.lang.String[] { "Title", "Description", "Language", "Category", });
    internal_static_AddCourseResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AddCourseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddCourseResponse_descriptor,
        new java.lang.String[] { "Course", });
    internal_static_GetUsersRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetUsersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetUsersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetUsersResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetUsersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetUsersResponse_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", "Roles", });
    internal_static_Role_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Role_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Role_descriptor,
        new java.lang.String[] { "Role", });
    internal_static_AddUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_AddUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddUserRequest_descriptor,
        new java.lang.String[] { "Username", "Password", "Roles", });
    internal_static_AddUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_AddUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_GetLearningStepRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_GetLearningStepRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetLearningStepRequest_descriptor,
        new java.lang.String[] { "CourseId", "StepNumber", });
    internal_static_GetLearningStepResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_GetLearningStepResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetLearningStepResponse_descriptor,
        new java.lang.String[] { "LearningStep", });
    internal_static_LearningStep_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_LearningStep_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LearningStep_descriptor,
        new java.lang.String[] { "CourseId", "StepOrder", "Content", "Type", });
    internal_static_CourseDraft_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_CourseDraft_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CourseDraft_descriptor,
        new java.lang.String[] { "Id", "Language", "Title", "Description", "TeacherId", "CourseId", "ApprovedBy", });
    internal_static_AddDraftRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_AddDraftRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddDraftRequest_descriptor,
        new java.lang.String[] { "Language", "Title", "Description", "TeacherId", });
    internal_static_AddDraftResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_AddDraftResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddDraftResponse_descriptor,
        new java.lang.String[] { "CourseDraft", });
    internal_static_GetDraftRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_GetDraftRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetDraftRequest_descriptor,
        new java.lang.String[] { "DraftId", });
    internal_static_GetDraftResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_GetDraftResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetDraftResponse_descriptor,
        new java.lang.String[] { "CourseDraft", });
    internal_static_UpdateLearningStepRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_UpdateLearningStepRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpdateLearningStepRequest_descriptor,
        new java.lang.String[] { "LearningStep", });
    internal_static_UpdateLearningStepResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_UpdateLearningStepResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpdateLearningStepResponse_descriptor,
        new java.lang.String[] { "LearningStep", });
    internal_static_UpdateDraftRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_UpdateDraftRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpdateDraftRequest_descriptor,
        new java.lang.String[] { "CourseDraft", });
    internal_static_UpdateDraftResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_UpdateDraftResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpdateDraftResponse_descriptor,
        new java.lang.String[] { "CourseDraft", });
    internal_static_GetDraftsRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_GetDraftsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetDraftsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetDraftsResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_GetDraftsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetDraftsResponse_descriptor,
        new java.lang.String[] { "Drafts", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
