// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public final class DataProtocol {
  private DataProtocol() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      DataProtocol.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCoursesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetCoursesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCoursesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetCoursesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Course_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Course_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddCourseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddCourseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddCourseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddCourseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUsersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetUsersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUsersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetUsersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Role_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Role_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetLearningStepRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetLearningStepRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetLearningStepResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetLearningStepResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LearningStep_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LearningStep_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CourseDraft_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CourseDraft_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddDraftRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddDraftRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddDraftResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddDraftResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDraftRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetDraftRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDraftResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetDraftResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CourseProgressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CourseProgressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CourseProgressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CourseProgressResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CourseProgressUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CourseProgressUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateLearningStepRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateLearningStepRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateLearningStepResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateLearningStepResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateDraftRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateDraftRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateDraftResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateDraftResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDraftsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetDraftsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDraftsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetDraftsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023data_protocol.proto\"$\n\021GetCoursesReque" +
      "st\022\017\n\007user_id\030\001 \001(\005\".\n\022GetCoursesRespons" +
      "e\022\030\n\007courses\030\001 \003(\0132\007.Course\"q\n\006Course\022\n\n" +
      "\002id\030\001 \001(\005\022\r\n\005title\030\002 \001(\t\022\023\n\013description\030" +
      "\003 \001(\t\022\020\n\010language\030\004 \001(\t\022\020\n\010category\030\005 \001(" +
      "\t\022\023\n\013total_steps\030\006 \001(\005\"Z\n\020AddCourseReque" +
      "st\022\r\n\005title\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\020" +
      "\n\010language\030\003 \001(\t\022\020\n\010category\030\004 \001(\t\",\n\021Ad" +
      "dCourseResponse\022\027\n\006course\030\001 \001(\0132\007.Course" +
      "\"\021\n\017GetUsersRequest\"(\n\020GetUsersResponse\022" +
      "\024\n\005users\030\001 \003(\0132\005.User\"L\n\004User\022\n\n\002id\030\001 \001(" +
      "\005\022\020\n\010username\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\024\n" +
      "\005roles\030\004 \003(\0132\005.Role\"\024\n\004Role\022\014\n\004role\030\001 \001(" +
      "\t\"C\n\016AddUserRequest\022\020\n\010username\030\001 \001(\t\022\020\n" +
      "\010password\030\002 \001(\t\022\r\n\005roles\030\003 \003(\t\"&\n\017AddUse" +
      "rResponse\022\023\n\004user\030\001 \001(\0132\005.User\"@\n\026GetLea" +
      "rningStepRequest\022\021\n\tcourse_id\030\001 \001(\005\022\023\n\013s" +
      "tep_number\030\002 \001(\005\"?\n\027GetLearningStepRespo" +
      "nse\022$\n\rlearning_step\030\001 \001(\0132\r.LearningSte" +
      "p\"T\n\014LearningStep\022\021\n\tcourse_id\030\001 \001(\005\022\022\n\n" +
      "step_order\030\002 \001(\005\022\017\n\007content\030\003 \001(\t\022\014\n\004typ" +
      "e\030\004 \001(\t\"\213\001\n\013CourseDraft\022\n\n\002id\030\001 \001(\005\022\020\n\010l" +
      "anguage\030\002 \001(\t\022\r\n\005title\030\003 \001(\t\022\023\n\013descript" +
      "ion\030\004 \001(\t\022\022\n\nteacher_id\030\005 \001(\005\022\021\n\tcourse_" +
      "id\030\006 \001(\005\022\023\n\013approved_by\030\007 \001(\005\"[\n\017AddDraf" +
      "tRequest\022\020\n\010language\030\001 \001(\t\022\r\n\005title\030\002 \001(" +
      "\t\022\023\n\013description\030\003 \001(\t\022\022\n\nteacher_id\030\004 \001" +
      "(\005\"5\n\020AddDraftResponse\022!\n\013courseDraft\030\001 " +
      "\001(\0132\014.CourseDraft\"\"\n\017GetDraftRequest\022\017\n\007" +
      "draftId\030\001 \001(\005\"5\n\020GetDraftResponse\022!\n\013cou" +
      "rseDraft\030\001 \001(\0132\014.CourseDraft\";\n\025CoursePr" +
      "ogressRequest\022\017\n\007user_id\030\001 \001(\005\022\021\n\tcourse" +
      "_id\030\002 \001(\005\".\n\026CourseProgressResponse\022\024\n\014c" +
      "urrent_step\030\001 \001(\005\"P\n\024CourseProgressUpdat" +
      "e\022\017\n\007user_id\030\001 \001(\005\022\021\n\tcourse_id\030\002 \001(\005\022\024\n" +
      "\014current_step\030\003 \001(\005\"\007\n\005Empty\"A\n\031UpdateLe" +
      "arningStepRequest\022$\n\rlearning_step\030\001 \001(\013" +
      "2\r.LearningStep\"B\n\032UpdateLearningStepRes" +
      "ponse\022$\n\rlearning_step\030\001 \001(\0132\r.LearningS" +
      "tep\"7\n\022UpdateDraftRequest\022!\n\013courseDraft" +
      "\030\001 \001(\0132\014.CourseDraft\"8\n\023UpdateDraftRespo" +
      "nse\022!\n\013courseDraft\030\001 \001(\0132\014.CourseDraft\"\022" +
      "\n\020GetDraftsRequest\"1\n\021GetDraftsResponse\022" +
      "\034\n\006drafts\030\001 \003(\0132\014.CourseDraft2\302\005\n\024DataRe" +
      "trievalService\022/\n\010GetUsers\022\020.GetUsersReq" +
      "uest\032\021.GetUsersResponse\022,\n\007AddUser\022\017.Add" +
      "UserRequest\032\020.AddUserResponse\0225\n\nGetCour" +
      "ses\022\022.GetCoursesRequest\032\023.GetCoursesResp" +
      "onse\0222\n\tAddCourse\022\021.AddCourseRequest\032\022.A" +
      "ddCourseResponse\022D\n\017GetLearningStep\022\027.Ge" +
      "tLearningStepRequest\032\030.GetLearningStepRe" +
      "sponse\022/\n\010AddDraft\022\020.AddDraftRequest\032\021.A" +
      "ddDraftResponse\022/\n\010GetDraft\022\020.GetDraftRe" +
      "quest\032\021.GetDraftResponse\0228\n\013UpdateDraft\022" +
      "\023.UpdateDraftRequest\032\024.UpdateDraftRespon" +
      "se\022D\n\021GetCourseProgress\022\026.CourseProgress" +
      "Request\032\027.CourseProgressResponse\0225\n\024Upda" +
      "teCourseProgress\022\025.CourseProgressUpdate\032" +
      "\006.Empty\022M\n\022UpdateLearningStep\022\032.UpdateLe" +
      "arningStepRequest\032\033.UpdateLearningStepRe" +
      "sponse\0222\n\tGetDrafts\022\021.GetDraftsRequest\032\022" +
      ".GetDraftsResponseB7\n\030via.sep3.dataserve" +
      "r.grpcP\001\252\002\030via.sep3.dataserver.grpcb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetCoursesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetCoursesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetCoursesRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_GetCoursesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetCoursesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetCoursesResponse_descriptor,
        new java.lang.String[] { "Courses", });
    internal_static_Course_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Course_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Course_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "Language", "Category", "TotalSteps", });
    internal_static_AddCourseRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AddCourseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddCourseRequest_descriptor,
        new java.lang.String[] { "Title", "Description", "Language", "Category", });
    internal_static_AddCourseResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AddCourseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddCourseResponse_descriptor,
        new java.lang.String[] { "Course", });
    internal_static_GetUsersRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetUsersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetUsersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetUsersResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetUsersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetUsersResponse_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", "Roles", });
    internal_static_Role_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Role_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Role_descriptor,
        new java.lang.String[] { "Role", });
    internal_static_AddUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_AddUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddUserRequest_descriptor,
        new java.lang.String[] { "Username", "Password", "Roles", });
    internal_static_AddUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_AddUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_GetLearningStepRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_GetLearningStepRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetLearningStepRequest_descriptor,
        new java.lang.String[] { "CourseId", "StepNumber", });
    internal_static_GetLearningStepResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_GetLearningStepResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetLearningStepResponse_descriptor,
        new java.lang.String[] { "LearningStep", });
    internal_static_LearningStep_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_LearningStep_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LearningStep_descriptor,
        new java.lang.String[] { "CourseId", "StepOrder", "Content", "Type", });
    internal_static_CourseDraft_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_CourseDraft_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CourseDraft_descriptor,
        new java.lang.String[] { "Id", "Language", "Title", "Description", "TeacherId", "CourseId", "ApprovedBy", });
    internal_static_AddDraftRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_AddDraftRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddDraftRequest_descriptor,
        new java.lang.String[] { "Language", "Title", "Description", "TeacherId", });
    internal_static_AddDraftResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_AddDraftResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddDraftResponse_descriptor,
        new java.lang.String[] { "CourseDraft", });
    internal_static_GetDraftRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_GetDraftRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetDraftRequest_descriptor,
        new java.lang.String[] { "DraftId", });
    internal_static_GetDraftResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_GetDraftResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetDraftResponse_descriptor,
        new java.lang.String[] { "CourseDraft", });
    internal_static_CourseProgressRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_CourseProgressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CourseProgressRequest_descriptor,
        new java.lang.String[] { "UserId", "CourseId", });
    internal_static_CourseProgressResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_CourseProgressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CourseProgressResponse_descriptor,
        new java.lang.String[] { "CurrentStep", });
    internal_static_CourseProgressUpdate_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_CourseProgressUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CourseProgressUpdate_descriptor,
        new java.lang.String[] { "UserId", "CourseId", "CurrentStep", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_UpdateLearningStepRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_UpdateLearningStepRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpdateLearningStepRequest_descriptor,
        new java.lang.String[] { "LearningStep", });
    internal_static_UpdateLearningStepResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_UpdateLearningStepResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpdateLearningStepResponse_descriptor,
        new java.lang.String[] { "LearningStep", });
    internal_static_UpdateDraftRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_UpdateDraftRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpdateDraftRequest_descriptor,
        new java.lang.String[] { "CourseDraft", });
    internal_static_UpdateDraftResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_UpdateDraftResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpdateDraftResponse_descriptor,
        new java.lang.String[] { "CourseDraft", });
    internal_static_GetDraftsRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_GetDraftsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetDraftsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetDraftsResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_GetDraftsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetDraftsResponse_descriptor,
        new java.lang.String[] { "Drafts", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
