// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface GetDraftRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetDraftRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 draftId = 1;</code>
   * @return The draftId.
   */
  int getDraftId();
}
