// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

/**
 * Protobuf type {@code GetDraftsResponse}
 */
@com.google.protobuf.Generated
public final class GetDraftsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:GetDraftsResponse)
    GetDraftsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      GetDraftsResponse.class.getName());
  }
  // Use GetDraftsResponse.newBuilder() to construct.
  private GetDraftsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetDraftsResponse() {
    drafts_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.dataserver.grpc.DataProtocol.internal_static_GetDraftsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.dataserver.grpc.DataProtocol.internal_static_GetDraftsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.dataserver.grpc.GetDraftsResponse.class, via.sep3.dataserver.grpc.GetDraftsResponse.Builder.class);
  }

  public static final int DRAFTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<via.sep3.dataserver.grpc.CourseDraft> drafts_;
  /**
   * <code>repeated .CourseDraft drafts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sep3.dataserver.grpc.CourseDraft> getDraftsList() {
    return drafts_;
  }
  /**
   * <code>repeated .CourseDraft drafts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sep3.dataserver.grpc.CourseDraftOrBuilder> 
      getDraftsOrBuilderList() {
    return drafts_;
  }
  /**
   * <code>repeated .CourseDraft drafts = 1;</code>
   */
  @java.lang.Override
  public int getDraftsCount() {
    return drafts_.size();
  }
  /**
   * <code>repeated .CourseDraft drafts = 1;</code>
   */
  @java.lang.Override
  public via.sep3.dataserver.grpc.CourseDraft getDrafts(int index) {
    return drafts_.get(index);
  }
  /**
   * <code>repeated .CourseDraft drafts = 1;</code>
   */
  @java.lang.Override
  public via.sep3.dataserver.grpc.CourseDraftOrBuilder getDraftsOrBuilder(
      int index) {
    return drafts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < drafts_.size(); i++) {
      output.writeMessage(1, drafts_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < drafts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, drafts_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.dataserver.grpc.GetDraftsResponse)) {
      return super.equals(obj);
    }
    via.sep3.dataserver.grpc.GetDraftsResponse other = (via.sep3.dataserver.grpc.GetDraftsResponse) obj;

    if (!getDraftsList()
        .equals(other.getDraftsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDraftsCount() > 0) {
      hash = (37 * hash) + DRAFTS_FIELD_NUMBER;
      hash = (53 * hash) + getDraftsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.dataserver.grpc.GetDraftsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.dataserver.grpc.GetDraftsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.GetDraftsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.dataserver.grpc.GetDraftsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.GetDraftsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.dataserver.grpc.GetDraftsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.GetDraftsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.dataserver.grpc.GetDraftsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static via.sep3.dataserver.grpc.GetDraftsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static via.sep3.dataserver.grpc.GetDraftsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.GetDraftsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.dataserver.grpc.GetDraftsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.dataserver.grpc.GetDraftsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetDraftsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetDraftsResponse)
      via.sep3.dataserver.grpc.GetDraftsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.dataserver.grpc.DataProtocol.internal_static_GetDraftsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.dataserver.grpc.DataProtocol.internal_static_GetDraftsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.dataserver.grpc.GetDraftsResponse.class, via.sep3.dataserver.grpc.GetDraftsResponse.Builder.class);
    }

    // Construct using via.sep3.dataserver.grpc.GetDraftsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (draftsBuilder_ == null) {
        drafts_ = java.util.Collections.emptyList();
      } else {
        drafts_ = null;
        draftsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.dataserver.grpc.DataProtocol.internal_static_GetDraftsResponse_descriptor;
    }

    @java.lang.Override
    public via.sep3.dataserver.grpc.GetDraftsResponse getDefaultInstanceForType() {
      return via.sep3.dataserver.grpc.GetDraftsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.dataserver.grpc.GetDraftsResponse build() {
      via.sep3.dataserver.grpc.GetDraftsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.dataserver.grpc.GetDraftsResponse buildPartial() {
      via.sep3.dataserver.grpc.GetDraftsResponse result = new via.sep3.dataserver.grpc.GetDraftsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(via.sep3.dataserver.grpc.GetDraftsResponse result) {
      if (draftsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          drafts_ = java.util.Collections.unmodifiableList(drafts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.drafts_ = drafts_;
      } else {
        result.drafts_ = draftsBuilder_.build();
      }
    }

    private void buildPartial0(via.sep3.dataserver.grpc.GetDraftsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.dataserver.grpc.GetDraftsResponse) {
        return mergeFrom((via.sep3.dataserver.grpc.GetDraftsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.dataserver.grpc.GetDraftsResponse other) {
      if (other == via.sep3.dataserver.grpc.GetDraftsResponse.getDefaultInstance()) return this;
      if (draftsBuilder_ == null) {
        if (!other.drafts_.isEmpty()) {
          if (drafts_.isEmpty()) {
            drafts_ = other.drafts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDraftsIsMutable();
            drafts_.addAll(other.drafts_);
          }
          onChanged();
        }
      } else {
        if (!other.drafts_.isEmpty()) {
          if (draftsBuilder_.isEmpty()) {
            draftsBuilder_.dispose();
            draftsBuilder_ = null;
            drafts_ = other.drafts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            draftsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetDraftsFieldBuilder() : null;
          } else {
            draftsBuilder_.addAllMessages(other.drafts_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              via.sep3.dataserver.grpc.CourseDraft m =
                  input.readMessage(
                      via.sep3.dataserver.grpc.CourseDraft.parser(),
                      extensionRegistry);
              if (draftsBuilder_ == null) {
                ensureDraftsIsMutable();
                drafts_.add(m);
              } else {
                draftsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sep3.dataserver.grpc.CourseDraft> drafts_ =
      java.util.Collections.emptyList();
    private void ensureDraftsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        drafts_ = new java.util.ArrayList<via.sep3.dataserver.grpc.CourseDraft>(drafts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        via.sep3.dataserver.grpc.CourseDraft, via.sep3.dataserver.grpc.CourseDraft.Builder, via.sep3.dataserver.grpc.CourseDraftOrBuilder> draftsBuilder_;

    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public java.util.List<via.sep3.dataserver.grpc.CourseDraft> getDraftsList() {
      if (draftsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(drafts_);
      } else {
        return draftsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public int getDraftsCount() {
      if (draftsBuilder_ == null) {
        return drafts_.size();
      } else {
        return draftsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public via.sep3.dataserver.grpc.CourseDraft getDrafts(int index) {
      if (draftsBuilder_ == null) {
        return drafts_.get(index);
      } else {
        return draftsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public Builder setDrafts(
        int index, via.sep3.dataserver.grpc.CourseDraft value) {
      if (draftsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDraftsIsMutable();
        drafts_.set(index, value);
        onChanged();
      } else {
        draftsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public Builder setDrafts(
        int index, via.sep3.dataserver.grpc.CourseDraft.Builder builderForValue) {
      if (draftsBuilder_ == null) {
        ensureDraftsIsMutable();
        drafts_.set(index, builderForValue.build());
        onChanged();
      } else {
        draftsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public Builder addDrafts(via.sep3.dataserver.grpc.CourseDraft value) {
      if (draftsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDraftsIsMutable();
        drafts_.add(value);
        onChanged();
      } else {
        draftsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public Builder addDrafts(
        int index, via.sep3.dataserver.grpc.CourseDraft value) {
      if (draftsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDraftsIsMutable();
        drafts_.add(index, value);
        onChanged();
      } else {
        draftsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public Builder addDrafts(
        via.sep3.dataserver.grpc.CourseDraft.Builder builderForValue) {
      if (draftsBuilder_ == null) {
        ensureDraftsIsMutable();
        drafts_.add(builderForValue.build());
        onChanged();
      } else {
        draftsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public Builder addDrafts(
        int index, via.sep3.dataserver.grpc.CourseDraft.Builder builderForValue) {
      if (draftsBuilder_ == null) {
        ensureDraftsIsMutable();
        drafts_.add(index, builderForValue.build());
        onChanged();
      } else {
        draftsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public Builder addAllDrafts(
        java.lang.Iterable<? extends via.sep3.dataserver.grpc.CourseDraft> values) {
      if (draftsBuilder_ == null) {
        ensureDraftsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, drafts_);
        onChanged();
      } else {
        draftsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public Builder clearDrafts() {
      if (draftsBuilder_ == null) {
        drafts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        draftsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public Builder removeDrafts(int index) {
      if (draftsBuilder_ == null) {
        ensureDraftsIsMutable();
        drafts_.remove(index);
        onChanged();
      } else {
        draftsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public via.sep3.dataserver.grpc.CourseDraft.Builder getDraftsBuilder(
        int index) {
      return internalGetDraftsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public via.sep3.dataserver.grpc.CourseDraftOrBuilder getDraftsOrBuilder(
        int index) {
      if (draftsBuilder_ == null) {
        return drafts_.get(index);  } else {
        return draftsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public java.util.List<? extends via.sep3.dataserver.grpc.CourseDraftOrBuilder> 
         getDraftsOrBuilderList() {
      if (draftsBuilder_ != null) {
        return draftsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(drafts_);
      }
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public via.sep3.dataserver.grpc.CourseDraft.Builder addDraftsBuilder() {
      return internalGetDraftsFieldBuilder().addBuilder(
          via.sep3.dataserver.grpc.CourseDraft.getDefaultInstance());
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public via.sep3.dataserver.grpc.CourseDraft.Builder addDraftsBuilder(
        int index) {
      return internalGetDraftsFieldBuilder().addBuilder(
          index, via.sep3.dataserver.grpc.CourseDraft.getDefaultInstance());
    }
    /**
     * <code>repeated .CourseDraft drafts = 1;</code>
     */
    public java.util.List<via.sep3.dataserver.grpc.CourseDraft.Builder> 
         getDraftsBuilderList() {
      return internalGetDraftsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        via.sep3.dataserver.grpc.CourseDraft, via.sep3.dataserver.grpc.CourseDraft.Builder, via.sep3.dataserver.grpc.CourseDraftOrBuilder> 
        internalGetDraftsFieldBuilder() {
      if (draftsBuilder_ == null) {
        draftsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            via.sep3.dataserver.grpc.CourseDraft, via.sep3.dataserver.grpc.CourseDraft.Builder, via.sep3.dataserver.grpc.CourseDraftOrBuilder>(
                drafts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        drafts_ = null;
      }
      return draftsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:GetDraftsResponse)
  }

  // @@protoc_insertion_point(class_scope:GetDraftsResponse)
  private static final via.sep3.dataserver.grpc.GetDraftsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.dataserver.grpc.GetDraftsResponse();
  }

  public static via.sep3.dataserver.grpc.GetDraftsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetDraftsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetDraftsResponse>() {
    @java.lang.Override
    public GetDraftsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetDraftsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetDraftsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.dataserver.grpc.GetDraftsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

