// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface GetDraftsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetDraftsRequest)
    com.google.protobuf.MessageOrBuilder {
}
