// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface GetDraftsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetDraftsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .CourseDraft drafts = 1;</code>
   */
  java.util.List<via.sep3.dataserver.grpc.CourseDraft> 
      getDraftsList();
  /**
   * <code>repeated .CourseDraft drafts = 1;</code>
   */
  via.sep3.dataserver.grpc.CourseDraft getDrafts(int index);
  /**
   * <code>repeated .CourseDraft drafts = 1;</code>
   */
  int getDraftsCount();
  /**
   * <code>repeated .CourseDraft drafts = 1;</code>
   */
  java.util.List<? extends via.sep3.dataserver.grpc.CourseDraftOrBuilder> 
      getDraftsOrBuilderList();
  /**
   * <code>repeated .CourseDraft drafts = 1;</code>
   */
  via.sep3.dataserver.grpc.CourseDraftOrBuilder getDraftsOrBuilder(
      int index);
}
