// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

/**
 * Protobuf type {@code GetLearningStepsResponse}
 */
@com.google.protobuf.Generated
public final class GetLearningStepsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:GetLearningStepsResponse)
    GetLearningStepsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      GetLearningStepsResponse.class.getName());
  }
  // Use GetLearningStepsResponse.newBuilder() to construct.
  private GetLearningStepsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetLearningStepsResponse() {
    learningSteps_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.dataserver.grpc.DataProtocol.internal_static_GetLearningStepsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.dataserver.grpc.DataProtocol.internal_static_GetLearningStepsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.dataserver.grpc.GetLearningStepsResponse.class, via.sep3.dataserver.grpc.GetLearningStepsResponse.Builder.class);
  }

  public static final int LEARNING_STEPS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<via.sep3.dataserver.grpc.LearningStep> learningSteps_;
  /**
   * <code>repeated .LearningStep learning_steps = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sep3.dataserver.grpc.LearningStep> getLearningStepsList() {
    return learningSteps_;
  }
  /**
   * <code>repeated .LearningStep learning_steps = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sep3.dataserver.grpc.LearningStepOrBuilder> 
      getLearningStepsOrBuilderList() {
    return learningSteps_;
  }
  /**
   * <code>repeated .LearningStep learning_steps = 1;</code>
   */
  @java.lang.Override
  public int getLearningStepsCount() {
    return learningSteps_.size();
  }
  /**
   * <code>repeated .LearningStep learning_steps = 1;</code>
   */
  @java.lang.Override
  public via.sep3.dataserver.grpc.LearningStep getLearningSteps(int index) {
    return learningSteps_.get(index);
  }
  /**
   * <code>repeated .LearningStep learning_steps = 1;</code>
   */
  @java.lang.Override
  public via.sep3.dataserver.grpc.LearningStepOrBuilder getLearningStepsOrBuilder(
      int index) {
    return learningSteps_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < learningSteps_.size(); i++) {
      output.writeMessage(1, learningSteps_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < learningSteps_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, learningSteps_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.dataserver.grpc.GetLearningStepsResponse)) {
      return super.equals(obj);
    }
    via.sep3.dataserver.grpc.GetLearningStepsResponse other = (via.sep3.dataserver.grpc.GetLearningStepsResponse) obj;

    if (!getLearningStepsList()
        .equals(other.getLearningStepsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLearningStepsCount() > 0) {
      hash = (37 * hash) + LEARNING_STEPS_FIELD_NUMBER;
      hash = (53 * hash) + getLearningStepsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.dataserver.grpc.GetLearningStepsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.dataserver.grpc.GetLearningStepsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.GetLearningStepsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.dataserver.grpc.GetLearningStepsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.GetLearningStepsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.dataserver.grpc.GetLearningStepsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.GetLearningStepsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.dataserver.grpc.GetLearningStepsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static via.sep3.dataserver.grpc.GetLearningStepsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static via.sep3.dataserver.grpc.GetLearningStepsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.GetLearningStepsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.dataserver.grpc.GetLearningStepsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.dataserver.grpc.GetLearningStepsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetLearningStepsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetLearningStepsResponse)
      via.sep3.dataserver.grpc.GetLearningStepsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.dataserver.grpc.DataProtocol.internal_static_GetLearningStepsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.dataserver.grpc.DataProtocol.internal_static_GetLearningStepsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.dataserver.grpc.GetLearningStepsResponse.class, via.sep3.dataserver.grpc.GetLearningStepsResponse.Builder.class);
    }

    // Construct using via.sep3.dataserver.grpc.GetLearningStepsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (learningStepsBuilder_ == null) {
        learningSteps_ = java.util.Collections.emptyList();
      } else {
        learningSteps_ = null;
        learningStepsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.dataserver.grpc.DataProtocol.internal_static_GetLearningStepsResponse_descriptor;
    }

    @java.lang.Override
    public via.sep3.dataserver.grpc.GetLearningStepsResponse getDefaultInstanceForType() {
      return via.sep3.dataserver.grpc.GetLearningStepsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.dataserver.grpc.GetLearningStepsResponse build() {
      via.sep3.dataserver.grpc.GetLearningStepsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.dataserver.grpc.GetLearningStepsResponse buildPartial() {
      via.sep3.dataserver.grpc.GetLearningStepsResponse result = new via.sep3.dataserver.grpc.GetLearningStepsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(via.sep3.dataserver.grpc.GetLearningStepsResponse result) {
      if (learningStepsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          learningSteps_ = java.util.Collections.unmodifiableList(learningSteps_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.learningSteps_ = learningSteps_;
      } else {
        result.learningSteps_ = learningStepsBuilder_.build();
      }
    }

    private void buildPartial0(via.sep3.dataserver.grpc.GetLearningStepsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.dataserver.grpc.GetLearningStepsResponse) {
        return mergeFrom((via.sep3.dataserver.grpc.GetLearningStepsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.dataserver.grpc.GetLearningStepsResponse other) {
      if (other == via.sep3.dataserver.grpc.GetLearningStepsResponse.getDefaultInstance()) return this;
      if (learningStepsBuilder_ == null) {
        if (!other.learningSteps_.isEmpty()) {
          if (learningSteps_.isEmpty()) {
            learningSteps_ = other.learningSteps_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLearningStepsIsMutable();
            learningSteps_.addAll(other.learningSteps_);
          }
          onChanged();
        }
      } else {
        if (!other.learningSteps_.isEmpty()) {
          if (learningStepsBuilder_.isEmpty()) {
            learningStepsBuilder_.dispose();
            learningStepsBuilder_ = null;
            learningSteps_ = other.learningSteps_;
            bitField0_ = (bitField0_ & ~0x00000001);
            learningStepsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetLearningStepsFieldBuilder() : null;
          } else {
            learningStepsBuilder_.addAllMessages(other.learningSteps_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              via.sep3.dataserver.grpc.LearningStep m =
                  input.readMessage(
                      via.sep3.dataserver.grpc.LearningStep.parser(),
                      extensionRegistry);
              if (learningStepsBuilder_ == null) {
                ensureLearningStepsIsMutable();
                learningSteps_.add(m);
              } else {
                learningStepsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sep3.dataserver.grpc.LearningStep> learningSteps_ =
      java.util.Collections.emptyList();
    private void ensureLearningStepsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        learningSteps_ = new java.util.ArrayList<via.sep3.dataserver.grpc.LearningStep>(learningSteps_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        via.sep3.dataserver.grpc.LearningStep, via.sep3.dataserver.grpc.LearningStep.Builder, via.sep3.dataserver.grpc.LearningStepOrBuilder> learningStepsBuilder_;

    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public java.util.List<via.sep3.dataserver.grpc.LearningStep> getLearningStepsList() {
      if (learningStepsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(learningSteps_);
      } else {
        return learningStepsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public int getLearningStepsCount() {
      if (learningStepsBuilder_ == null) {
        return learningSteps_.size();
      } else {
        return learningStepsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public via.sep3.dataserver.grpc.LearningStep getLearningSteps(int index) {
      if (learningStepsBuilder_ == null) {
        return learningSteps_.get(index);
      } else {
        return learningStepsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public Builder setLearningSteps(
        int index, via.sep3.dataserver.grpc.LearningStep value) {
      if (learningStepsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLearningStepsIsMutable();
        learningSteps_.set(index, value);
        onChanged();
      } else {
        learningStepsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public Builder setLearningSteps(
        int index, via.sep3.dataserver.grpc.LearningStep.Builder builderForValue) {
      if (learningStepsBuilder_ == null) {
        ensureLearningStepsIsMutable();
        learningSteps_.set(index, builderForValue.build());
        onChanged();
      } else {
        learningStepsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public Builder addLearningSteps(via.sep3.dataserver.grpc.LearningStep value) {
      if (learningStepsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLearningStepsIsMutable();
        learningSteps_.add(value);
        onChanged();
      } else {
        learningStepsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public Builder addLearningSteps(
        int index, via.sep3.dataserver.grpc.LearningStep value) {
      if (learningStepsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLearningStepsIsMutable();
        learningSteps_.add(index, value);
        onChanged();
      } else {
        learningStepsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public Builder addLearningSteps(
        via.sep3.dataserver.grpc.LearningStep.Builder builderForValue) {
      if (learningStepsBuilder_ == null) {
        ensureLearningStepsIsMutable();
        learningSteps_.add(builderForValue.build());
        onChanged();
      } else {
        learningStepsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public Builder addLearningSteps(
        int index, via.sep3.dataserver.grpc.LearningStep.Builder builderForValue) {
      if (learningStepsBuilder_ == null) {
        ensureLearningStepsIsMutable();
        learningSteps_.add(index, builderForValue.build());
        onChanged();
      } else {
        learningStepsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public Builder addAllLearningSteps(
        java.lang.Iterable<? extends via.sep3.dataserver.grpc.LearningStep> values) {
      if (learningStepsBuilder_ == null) {
        ensureLearningStepsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, learningSteps_);
        onChanged();
      } else {
        learningStepsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public Builder clearLearningSteps() {
      if (learningStepsBuilder_ == null) {
        learningSteps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        learningStepsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public Builder removeLearningSteps(int index) {
      if (learningStepsBuilder_ == null) {
        ensureLearningStepsIsMutable();
        learningSteps_.remove(index);
        onChanged();
      } else {
        learningStepsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public via.sep3.dataserver.grpc.LearningStep.Builder getLearningStepsBuilder(
        int index) {
      return internalGetLearningStepsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public via.sep3.dataserver.grpc.LearningStepOrBuilder getLearningStepsOrBuilder(
        int index) {
      if (learningStepsBuilder_ == null) {
        return learningSteps_.get(index);  } else {
        return learningStepsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public java.util.List<? extends via.sep3.dataserver.grpc.LearningStepOrBuilder> 
         getLearningStepsOrBuilderList() {
      if (learningStepsBuilder_ != null) {
        return learningStepsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(learningSteps_);
      }
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public via.sep3.dataserver.grpc.LearningStep.Builder addLearningStepsBuilder() {
      return internalGetLearningStepsFieldBuilder().addBuilder(
          via.sep3.dataserver.grpc.LearningStep.getDefaultInstance());
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public via.sep3.dataserver.grpc.LearningStep.Builder addLearningStepsBuilder(
        int index) {
      return internalGetLearningStepsFieldBuilder().addBuilder(
          index, via.sep3.dataserver.grpc.LearningStep.getDefaultInstance());
    }
    /**
     * <code>repeated .LearningStep learning_steps = 1;</code>
     */
    public java.util.List<via.sep3.dataserver.grpc.LearningStep.Builder> 
         getLearningStepsBuilderList() {
      return internalGetLearningStepsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        via.sep3.dataserver.grpc.LearningStep, via.sep3.dataserver.grpc.LearningStep.Builder, via.sep3.dataserver.grpc.LearningStepOrBuilder> 
        internalGetLearningStepsFieldBuilder() {
      if (learningStepsBuilder_ == null) {
        learningStepsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            via.sep3.dataserver.grpc.LearningStep, via.sep3.dataserver.grpc.LearningStep.Builder, via.sep3.dataserver.grpc.LearningStepOrBuilder>(
                learningSteps_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        learningSteps_ = null;
      }
      return learningStepsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:GetLearningStepsResponse)
  }

  // @@protoc_insertion_point(class_scope:GetLearningStepsResponse)
  private static final via.sep3.dataserver.grpc.GetLearningStepsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.dataserver.grpc.GetLearningStepsResponse();
  }

  public static via.sep3.dataserver.grpc.GetLearningStepsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetLearningStepsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetLearningStepsResponse>() {
    @java.lang.Override
    public GetLearningStepsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetLearningStepsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetLearningStepsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.dataserver.grpc.GetLearningStepsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

