// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface GetLearningStepRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetLearningStepRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 course_id = 1;</code>
   * @return The courseId.
   */
  int getCourseId();

  /**
   * <code>int32 step_number = 2;</code>
   * @return The stepNumber.
   */
  int getStepNumber();
}
