// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface GetLearningStepsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetLearningStepsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .LearningStep learningSteps = 1;</code>
   */
  java.util.List<via.sep3.dataserver.grpc.LearningStep> 
      getLearningStepsList();
  /**
   * <code>repeated .LearningStep learningSteps = 1;</code>
   */
  via.sep3.dataserver.grpc.LearningStep getLearningSteps(int index);
  /**
   * <code>repeated .LearningStep learningSteps = 1;</code>
   */
  int getLearningStepsCount();
  /**
   * <code>repeated .LearningStep learningSteps = 1;</code>
   */
  java.util.List<? extends via.sep3.dataserver.grpc.LearningStepOrBuilder> 
      getLearningStepsOrBuilderList();
  /**
   * <code>repeated .LearningStep learningSteps = 1;</code>
   */
  via.sep3.dataserver.grpc.LearningStepOrBuilder getLearningStepsOrBuilder(
      int index);
}
