// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface LeaderboardEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LeaderboardEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>int32 total_score = 2;</code>
   * @return The totalScore.
   */
  int getTotalScore();

  /**
   * <pre>
   * We will calculate this 1st, 2nd, 3rd logic in Java
   * </pre>
   *
   * <code>int32 rank = 3;</code>
   * @return The rank.
   */
  int getRank();
}
