// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

/**
 * <pre>
 * Single row in the leaderboard
 * </pre>
 *
 * Protobuf type {@code LeaderboardEntry}
 */
@com.google.protobuf.Generated
public final class LeaderboardEntry extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:LeaderboardEntry)
    LeaderboardEntryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      LeaderboardEntry.class.getName());
  }
  // Use LeaderboardEntry.newBuilder() to construct.
  private LeaderboardEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LeaderboardEntry() {
    username_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.dataserver.grpc.DataProtocol.internal_static_LeaderboardEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.dataserver.grpc.DataProtocol.internal_static_LeaderboardEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.dataserver.grpc.LeaderboardEntry.class, via.sep3.dataserver.grpc.LeaderboardEntry.Builder.class);
  }

  public static final int USERNAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object username_ = "";
  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_SCORE_FIELD_NUMBER = 2;
  private int totalScore_ = 0;
  /**
   * <code>int32 total_score = 2;</code>
   * @return The totalScore.
   */
  @java.lang.Override
  public int getTotalScore() {
    return totalScore_;
  }

  public static final int RANK_FIELD_NUMBER = 3;
  private int rank_ = 0;
  /**
   * <pre>
   * We will calculate this 1st, 2nd, 3rd logic in Java
   * </pre>
   *
   * <code>int32 rank = 3;</code>
   * @return The rank.
   */
  @java.lang.Override
  public int getRank() {
    return rank_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, username_);
    }
    if (totalScore_ != 0) {
      output.writeInt32(2, totalScore_);
    }
    if (rank_ != 0) {
      output.writeInt32(3, rank_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, username_);
    }
    if (totalScore_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, totalScore_);
    }
    if (rank_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, rank_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.dataserver.grpc.LeaderboardEntry)) {
      return super.equals(obj);
    }
    via.sep3.dataserver.grpc.LeaderboardEntry other = (via.sep3.dataserver.grpc.LeaderboardEntry) obj;

    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (getTotalScore()
        != other.getTotalScore()) return false;
    if (getRank()
        != other.getRank()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + TOTAL_SCORE_FIELD_NUMBER;
    hash = (53 * hash) + getTotalScore();
    hash = (37 * hash) + RANK_FIELD_NUMBER;
    hash = (53 * hash) + getRank();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.dataserver.grpc.LeaderboardEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.dataserver.grpc.LeaderboardEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.LeaderboardEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.dataserver.grpc.LeaderboardEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.LeaderboardEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.dataserver.grpc.LeaderboardEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.LeaderboardEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.dataserver.grpc.LeaderboardEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static via.sep3.dataserver.grpc.LeaderboardEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static via.sep3.dataserver.grpc.LeaderboardEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.LeaderboardEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.dataserver.grpc.LeaderboardEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.dataserver.grpc.LeaderboardEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Single row in the leaderboard
   * </pre>
   *
   * Protobuf type {@code LeaderboardEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LeaderboardEntry)
      via.sep3.dataserver.grpc.LeaderboardEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.dataserver.grpc.DataProtocol.internal_static_LeaderboardEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.dataserver.grpc.DataProtocol.internal_static_LeaderboardEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.dataserver.grpc.LeaderboardEntry.class, via.sep3.dataserver.grpc.LeaderboardEntry.Builder.class);
    }

    // Construct using via.sep3.dataserver.grpc.LeaderboardEntry.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      username_ = "";
      totalScore_ = 0;
      rank_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.dataserver.grpc.DataProtocol.internal_static_LeaderboardEntry_descriptor;
    }

    @java.lang.Override
    public via.sep3.dataserver.grpc.LeaderboardEntry getDefaultInstanceForType() {
      return via.sep3.dataserver.grpc.LeaderboardEntry.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.dataserver.grpc.LeaderboardEntry build() {
      via.sep3.dataserver.grpc.LeaderboardEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.dataserver.grpc.LeaderboardEntry buildPartial() {
      via.sep3.dataserver.grpc.LeaderboardEntry result = new via.sep3.dataserver.grpc.LeaderboardEntry(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(via.sep3.dataserver.grpc.LeaderboardEntry result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.username_ = username_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalScore_ = totalScore_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rank_ = rank_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.dataserver.grpc.LeaderboardEntry) {
        return mergeFrom((via.sep3.dataserver.grpc.LeaderboardEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.dataserver.grpc.LeaderboardEntry other) {
      if (other == via.sep3.dataserver.grpc.LeaderboardEntry.getDefaultInstance()) return this;
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTotalScore() != 0) {
        setTotalScore(other.getTotalScore());
      }
      if (other.getRank() != 0) {
        setRank(other.getRank());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              username_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              totalScore_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              rank_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 1;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      username_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      username_ = getDefaultInstance().getUsername();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      username_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int totalScore_ ;
    /**
     * <code>int32 total_score = 2;</code>
     * @return The totalScore.
     */
    @java.lang.Override
    public int getTotalScore() {
      return totalScore_;
    }
    /**
     * <code>int32 total_score = 2;</code>
     * @param value The totalScore to set.
     * @return This builder for chaining.
     */
    public Builder setTotalScore(int value) {

      totalScore_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_score = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalScore() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalScore_ = 0;
      onChanged();
      return this;
    }

    private int rank_ ;
    /**
     * <pre>
     * We will calculate this 1st, 2nd, 3rd logic in Java
     * </pre>
     *
     * <code>int32 rank = 3;</code>
     * @return The rank.
     */
    @java.lang.Override
    public int getRank() {
      return rank_;
    }
    /**
     * <pre>
     * We will calculate this 1st, 2nd, 3rd logic in Java
     * </pre>
     *
     * <code>int32 rank = 3;</code>
     * @param value The rank to set.
     * @return This builder for chaining.
     */
    public Builder setRank(int value) {

      rank_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * We will calculate this 1st, 2nd, 3rd logic in Java
     * </pre>
     *
     * <code>int32 rank = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRank() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rank_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:LeaderboardEntry)
  }

  // @@protoc_insertion_point(class_scope:LeaderboardEntry)
  private static final via.sep3.dataserver.grpc.LeaderboardEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.dataserver.grpc.LeaderboardEntry();
  }

  public static via.sep3.dataserver.grpc.LeaderboardEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LeaderboardEntry>
      PARSER = new com.google.protobuf.AbstractParser<LeaderboardEntry>() {
    @java.lang.Override
    public LeaderboardEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LeaderboardEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LeaderboardEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.dataserver.grpc.LeaderboardEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

