// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface LearningStepOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LearningStep)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Part of PK
   * </pre>
   *
   * <code>int32 course_id = 1;</code>
   * @return The courseId.
   */
  int getCourseId();

  /**
   * <pre>
   * Part of PK
   * </pre>
   *
   * <code>int32 step_order = 2;</code>
   * @return The stepOrder.
   */
  int getStepOrder();

  /**
   * <pre>
   * Field 3
   * </pre>
   *
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * Field 3
   * </pre>
   *
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * Field 4
   * </pre>
   *
   * <code>string type = 4;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * Field 4
   * </pre>
   *
   * <code>string type = 4;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
