// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface LearningStepKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LearningStepKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 course_id = 1;</code>
   * @return The courseId.
   */
  int getCourseId();

  /**
   * <code>int32 step_order = 2;</code>
   * @return The stepOrder.
   */
  int getStepOrder();
}
