// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface SystemUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SystemUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password_hash = 3;</code>
   * @return The passwordHash.
   */
  java.lang.String getPasswordHash();
  /**
   * <code>string password_hash = 3;</code>
   * @return The bytes for passwordHash.
   */
  com.google.protobuf.ByteString
      getPasswordHashBytes();

  /**
   * <code>repeated .Role roles = 4;</code>
   */
  java.util.List<via.sep3.dataserver.grpc.Role> 
      getRolesList();
  /**
   * <code>repeated .Role roles = 4;</code>
   */
  via.sep3.dataserver.grpc.Role getRoles(int index);
  /**
   * <code>repeated .Role roles = 4;</code>
   */
  int getRolesCount();
  /**
   * <code>repeated .Role roles = 4;</code>
   */
  java.util.List<? extends via.sep3.dataserver.grpc.RoleOrBuilder> 
      getRolesOrBuilderList();
  /**
   * <code>repeated .Role roles = 4;</code>
   */
  via.sep3.dataserver.grpc.RoleOrBuilder getRolesOrBuilder(
      int index);
}
