// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface SystemUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SystemUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password_hash = 3;</code>
   * @return The passwordHash.
   */
  java.lang.String getPasswordHash();
  /**
   * <code>string password_hash = 3;</code>
   * @return The bytes for passwordHash.
   */
  com.google.protobuf.ByteString
      getPasswordHashBytes();

  /**
   * <code>string role = 4;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 4;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();
}
