// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

/**
 * Protobuf type {@code UpdateDraftResponse}
 */
@com.google.protobuf.Generated
public final class UpdateDraftResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:UpdateDraftResponse)
    UpdateDraftResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      UpdateDraftResponse.class.getName());
  }
  // Use UpdateDraftResponse.newBuilder() to construct.
  private UpdateDraftResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateDraftResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.dataserver.grpc.DataProtocol.internal_static_UpdateDraftResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.dataserver.grpc.DataProtocol.internal_static_UpdateDraftResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.dataserver.grpc.UpdateDraftResponse.class, via.sep3.dataserver.grpc.UpdateDraftResponse.Builder.class);
  }

  private int bitField0_;
  public static final int COURSEDRAFT_FIELD_NUMBER = 1;
  private via.sep3.dataserver.grpc.CourseDraft courseDraft_;
  /**
   * <code>.CourseDraft courseDraft = 1;</code>
   * @return Whether the courseDraft field is set.
   */
  @java.lang.Override
  public boolean hasCourseDraft() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.CourseDraft courseDraft = 1;</code>
   * @return The courseDraft.
   */
  @java.lang.Override
  public via.sep3.dataserver.grpc.CourseDraft getCourseDraft() {
    return courseDraft_ == null ? via.sep3.dataserver.grpc.CourseDraft.getDefaultInstance() : courseDraft_;
  }
  /**
   * <code>.CourseDraft courseDraft = 1;</code>
   */
  @java.lang.Override
  public via.sep3.dataserver.grpc.CourseDraftOrBuilder getCourseDraftOrBuilder() {
    return courseDraft_ == null ? via.sep3.dataserver.grpc.CourseDraft.getDefaultInstance() : courseDraft_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCourseDraft());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCourseDraft());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.dataserver.grpc.UpdateDraftResponse)) {
      return super.equals(obj);
    }
    via.sep3.dataserver.grpc.UpdateDraftResponse other = (via.sep3.dataserver.grpc.UpdateDraftResponse) obj;

    if (hasCourseDraft() != other.hasCourseDraft()) return false;
    if (hasCourseDraft()) {
      if (!getCourseDraft()
          .equals(other.getCourseDraft())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCourseDraft()) {
      hash = (37 * hash) + COURSEDRAFT_FIELD_NUMBER;
      hash = (53 * hash) + getCourseDraft().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.dataserver.grpc.UpdateDraftResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.dataserver.grpc.UpdateDraftResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.UpdateDraftResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.dataserver.grpc.UpdateDraftResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.UpdateDraftResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.dataserver.grpc.UpdateDraftResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.UpdateDraftResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.dataserver.grpc.UpdateDraftResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static via.sep3.dataserver.grpc.UpdateDraftResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static via.sep3.dataserver.grpc.UpdateDraftResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.dataserver.grpc.UpdateDraftResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.dataserver.grpc.UpdateDraftResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.dataserver.grpc.UpdateDraftResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UpdateDraftResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UpdateDraftResponse)
      via.sep3.dataserver.grpc.UpdateDraftResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.dataserver.grpc.DataProtocol.internal_static_UpdateDraftResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.dataserver.grpc.DataProtocol.internal_static_UpdateDraftResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.dataserver.grpc.UpdateDraftResponse.class, via.sep3.dataserver.grpc.UpdateDraftResponse.Builder.class);
    }

    // Construct using via.sep3.dataserver.grpc.UpdateDraftResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCourseDraftFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      courseDraft_ = null;
      if (courseDraftBuilder_ != null) {
        courseDraftBuilder_.dispose();
        courseDraftBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.dataserver.grpc.DataProtocol.internal_static_UpdateDraftResponse_descriptor;
    }

    @java.lang.Override
    public via.sep3.dataserver.grpc.UpdateDraftResponse getDefaultInstanceForType() {
      return via.sep3.dataserver.grpc.UpdateDraftResponse.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.dataserver.grpc.UpdateDraftResponse build() {
      via.sep3.dataserver.grpc.UpdateDraftResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.dataserver.grpc.UpdateDraftResponse buildPartial() {
      via.sep3.dataserver.grpc.UpdateDraftResponse result = new via.sep3.dataserver.grpc.UpdateDraftResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(via.sep3.dataserver.grpc.UpdateDraftResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.courseDraft_ = courseDraftBuilder_ == null
            ? courseDraft_
            : courseDraftBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.dataserver.grpc.UpdateDraftResponse) {
        return mergeFrom((via.sep3.dataserver.grpc.UpdateDraftResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.dataserver.grpc.UpdateDraftResponse other) {
      if (other == via.sep3.dataserver.grpc.UpdateDraftResponse.getDefaultInstance()) return this;
      if (other.hasCourseDraft()) {
        mergeCourseDraft(other.getCourseDraft());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetCourseDraftFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private via.sep3.dataserver.grpc.CourseDraft courseDraft_;
    private com.google.protobuf.SingleFieldBuilder<
        via.sep3.dataserver.grpc.CourseDraft, via.sep3.dataserver.grpc.CourseDraft.Builder, via.sep3.dataserver.grpc.CourseDraftOrBuilder> courseDraftBuilder_;
    /**
     * <code>.CourseDraft courseDraft = 1;</code>
     * @return Whether the courseDraft field is set.
     */
    public boolean hasCourseDraft() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.CourseDraft courseDraft = 1;</code>
     * @return The courseDraft.
     */
    public via.sep3.dataserver.grpc.CourseDraft getCourseDraft() {
      if (courseDraftBuilder_ == null) {
        return courseDraft_ == null ? via.sep3.dataserver.grpc.CourseDraft.getDefaultInstance() : courseDraft_;
      } else {
        return courseDraftBuilder_.getMessage();
      }
    }
    /**
     * <code>.CourseDraft courseDraft = 1;</code>
     */
    public Builder setCourseDraft(via.sep3.dataserver.grpc.CourseDraft value) {
      if (courseDraftBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        courseDraft_ = value;
      } else {
        courseDraftBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.CourseDraft courseDraft = 1;</code>
     */
    public Builder setCourseDraft(
        via.sep3.dataserver.grpc.CourseDraft.Builder builderForValue) {
      if (courseDraftBuilder_ == null) {
        courseDraft_ = builderForValue.build();
      } else {
        courseDraftBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.CourseDraft courseDraft = 1;</code>
     */
    public Builder mergeCourseDraft(via.sep3.dataserver.grpc.CourseDraft value) {
      if (courseDraftBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          courseDraft_ != null &&
          courseDraft_ != via.sep3.dataserver.grpc.CourseDraft.getDefaultInstance()) {
          getCourseDraftBuilder().mergeFrom(value);
        } else {
          courseDraft_ = value;
        }
      } else {
        courseDraftBuilder_.mergeFrom(value);
      }
      if (courseDraft_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.CourseDraft courseDraft = 1;</code>
     */
    public Builder clearCourseDraft() {
      bitField0_ = (bitField0_ & ~0x00000001);
      courseDraft_ = null;
      if (courseDraftBuilder_ != null) {
        courseDraftBuilder_.dispose();
        courseDraftBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.CourseDraft courseDraft = 1;</code>
     */
    public via.sep3.dataserver.grpc.CourseDraft.Builder getCourseDraftBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetCourseDraftFieldBuilder().getBuilder();
    }
    /**
     * <code>.CourseDraft courseDraft = 1;</code>
     */
    public via.sep3.dataserver.grpc.CourseDraftOrBuilder getCourseDraftOrBuilder() {
      if (courseDraftBuilder_ != null) {
        return courseDraftBuilder_.getMessageOrBuilder();
      } else {
        return courseDraft_ == null ?
            via.sep3.dataserver.grpc.CourseDraft.getDefaultInstance() : courseDraft_;
      }
    }
    /**
     * <code>.CourseDraft courseDraft = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        via.sep3.dataserver.grpc.CourseDraft, via.sep3.dataserver.grpc.CourseDraft.Builder, via.sep3.dataserver.grpc.CourseDraftOrBuilder> 
        internalGetCourseDraftFieldBuilder() {
      if (courseDraftBuilder_ == null) {
        courseDraftBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            via.sep3.dataserver.grpc.CourseDraft, via.sep3.dataserver.grpc.CourseDraft.Builder, via.sep3.dataserver.grpc.CourseDraftOrBuilder>(
                getCourseDraft(),
                getParentForChildren(),
                isClean());
        courseDraft_ = null;
      }
      return courseDraftBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:UpdateDraftResponse)
  }

  // @@protoc_insertion_point(class_scope:UpdateDraftResponse)
  private static final via.sep3.dataserver.grpc.UpdateDraftResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.dataserver.grpc.UpdateDraftResponse();
  }

  public static via.sep3.dataserver.grpc.UpdateDraftResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateDraftResponse>
      PARSER = new com.google.protobuf.AbstractParser<UpdateDraftResponse>() {
    @java.lang.Override
    public UpdateDraftResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateDraftResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateDraftResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.dataserver.grpc.UpdateDraftResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

