// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface UpdateDraftRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateDraftRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CourseDraft courseDraft = 1;</code>
   * @return Whether the courseDraft field is set.
   */
  boolean hasCourseDraft();
  /**
   * <code>.CourseDraft courseDraft = 1;</code>
   * @return The courseDraft.
   */
  via.sep3.dataserver.grpc.CourseDraft getCourseDraft();
  /**
   * <code>.CourseDraft courseDraft = 1;</code>
   */
  via.sep3.dataserver.grpc.CourseDraftOrBuilder getCourseDraftOrBuilder();
}
