// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface UpdateCourseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateCourseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Course course = 1;</code>
   * @return Whether the course field is set.
   */
  boolean hasCourse();
  /**
   * <code>.Course course = 1;</code>
   * @return The course.
   */
  via.sep3.dataserver.grpc.Course getCourse();
  /**
   * <code>.Course course = 1;</code>
   */
  via.sep3.dataserver.grpc.CourseOrBuilder getCourseOrBuilder();
}
