// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data_protocol.proto
// Protobuf Java Version: 4.32.0

package via.sep3.dataserver.grpc;

@com.google.protobuf.Generated
public interface UpdateLearningStepRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateLearningStepRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.LearningStep learning_step = 1;</code>
   * @return Whether the learningStep field is set.
   */
  boolean hasLearningStep();
  /**
   * <code>.LearningStep learning_step = 1;</code>
   * @return The learningStep.
   */
  via.sep3.dataserver.grpc.LearningStep getLearningStep();
  /**
   * <code>.LearningStep learning_step = 1;</code>
   */
  via.sep3.dataserver.grpc.LearningStepOrBuilder getLearningStepOrBuilder();
}
