@startuml GetCoursesSD
!include .\astah-min.puml
scale 1

actor "Client" as C1
participant "LogicServer" as S1
participant "DataServer" as S2
participant "Database" as DB

C1 -> S1: (HTTPS) GET .../courses
S1 -> S2: (gRPC) GetCourses()
S2 -> DB: (SQL) SELECT * FROM Course
DB --> S2: List of Course records
S2 --> S1: (gRPC) (BIN) List of Course objects
S1 --> C1: (HTTP) 200 OK + (JSON) List of Course objects