@startuml GR
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml
scale 1

class Course
{
    id {PK}
    language {FK}
    title
    description
    category {FK}
}

class CourseCategory
{
    id {PK}
    name
    description
}

class Language
{
    code {PK}
    name
}

class SystemUser
{
    id {PK}
    username
    password_hash
}

class Role
{
    role {PK}
}

class SystemUserRole
{
    systemUserId {PPK, FK}
    role {PPK, FK}
}
class LearningStepType
{
    id {PK}
    name
}

class LearningStep
{
    step_order {PPK}
    course {PPK, FK}
    type {FK}
    content
}

class CourseDraft
{
    id {PK}
    language
    title
    description
    teacher_id {FK}
    course_id {FK}
    approved_by {FK}
}

Course "*" -- "1" CourseCategory
Course "*" -- "1" Language
SystemUser "1" -- "*" SystemUserRole
SystemUserRole "*" -- "1" Role
Course "1" -- "1" CourseDraft
CourseDraft "*" -- "1" SystemUser : approved_by ▼
CourseDraft "*" -- "1" SystemUser : created_by ▼

