@startuml
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml
|Admin|
start
fork
    :Manage system settings;
    :Add new category or language;
    |System|
    :Update platform options;
|Admin|
fork again
    :Manage user roles;
    :Select target user;
    :Assign or revoke role;
    |System|
    :Update user permissions;
end fork
:Confirm changes;
stop
@enduml
