@startuml
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml
|Learner|
start
:Access course catalog;
|System|
:Provide available categories and languages;
|Learner|
:Apply search filters;
|System|
:Filter courses based on criteria;
|Learner|
:Select a course;
:Enroll in course;
stop
@enduml
