@startuml
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml

|Teacher|
start
:Propose new course;

|System|
:Store course details as draft;

|Admin|
:Review pending drafts;

if (Is draft acceptable?) then (yes)
    partition Approve {
        :Approve draft;
        |System|
        :Update status to approved;
        :Initialize new course;
        |Teacher|
        :Start adding learning steps;
    }
else (no)
    partition Disapprove {
        |Admin|
        :Disapprove draft;
        |System|
        :Delete the draft;
    }
endif

stop
@enduml