@startuml
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml
|User|
start
:Access platform;
if (Has account?) then (no)
    :Register;
endif
:Log in;
|System|
:Authenticate user;
|Learner|
repeat
    :Browse course catalog;
    :Filter by category or language;
    :Enroll in course;
    repeat
        |System|
        :Provide learning step;
        |Learner|
        repeat
        :Complete learning step;
        |System|
        :Provide feedback;
        |Learner|
        repeat while (Activity not completed correctly?)
        |System|
        :Update points (leaderboard);
        |Learner|
    repeat while (Course not finished?)    
    :Check leaderboard position;
backward:Explore more courses;
repeat while (User wants to learn more?)
|User|
:Log out;
stop
@enduml
