@startuml
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml
start
:Teacher opens own courses;
:System retrieves courses assigned to teacher;
:Teacher selects course to edit;
:System provides course content;
:Teacher adds or edits learning step;
:System updates step content;
:Teacher saves changes;
:System confirms update;
stop
@enduml
