@startuml
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml
|Teacher|
start
:Open own courses;
|System|
:Retrieve courses assigned to teacher;
|Teacher|
:Select course to edit;
|System|
:Provide course content;
|Teacher|
:Add or edit learning step;
|System|
:Update step content;
|Teacher|
:Save changes;
|System|
:Confirm update;
stop
@enduml
