@startuml
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml
|User|
start
:Initiate registration;
|System|
:Request user details;
|User|
:Provide username and password;
|System|
:Validate user details;
if (User already exists?) then (yes)
    :Show error message;
    stop
else (no)
    :Create user account;
    :Confirm registration and log the user in;
endif

:Authenticate user;
:Grant access to platform;
stop
@enduml
