@startuml
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml
start
:User initiates registration;
:System requests user details;
:User provides username and password;
:System validates user details;
if (User already exists?) then (yes)
    :System shows error message;
    stop
else (no)
    :System creates user account;
    :System confirms registration and logs the user in;
endif

:System authenticates user;
:System grants access to platform;

@enduml
