@startuml DomainModel
!include .\astah-min.puml
scale 0.5
' ▶ ◀ ▲ ▼

skinparam ranksep 80
skinparam nodesep 80
skinparam ArrowFontSize 9

together {
    class User
    class Teacher
    class Administrator
}

class User
{
    id
}

together {
    class Course
    class LearningStep
}
class Course {
    id
    language
    category
    title
    description
}
class LearningStep {
    type
    content
}



Teacher "*" -down- "*" Course : Is assigned to ▼
Administrator "*" -down- "*" Course : Manages ▼
LearningStep "*" -down- "1" Course : Belongs to ▼
Teacher -up-|> User
Administrator -up-|> User
User "*" -left- "*" LearningStep : ◀ Completes
Administrator "*" -right- "*" Teacher : Manages ▶

@enduml