@startuml SSD03 Approve Draft
title SSD03 – Approve Draft
!include .\astah-min.puml

actor Administrator
participant Server

Administrator -> Server: Login/register
Server --> Administrator: Auth OK / session

Administrator -> Server: Request list of waiting for approval courses
Server --> Administrator: Display list of waiting for approval courses

Administrator -> Server: Select course to approve
Server --> Administrator: Present the course's information

Administrator -> Server: Approve the course to be created
Server --> Administrator: Confirmation of approval

@enduml
