@startuml SSD03 Approve Course
title SSD03 – Approve course
!include .\astah-min.puml

actor Administrator
participant Server

Administrator -> Server: Login/register
Server --> Administrator: Auth OK / session

Administrator -> Server: Request list of courses
Server --> Administrator: Display list of courses

Administrator -> Server: Select course to approve
Server --> Administrator: Present the course's information and data

Administrator -> Server: Approve the course to be created
Server --> Administrator: Confirmation of approval

@enduml
