@startuml UseCaseDiagram
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml

scale 2
left to right direction

actor "Learner" as s
package Internal {
    actor "Teacher" as t
    actor "Administrator" as a
}

t --|> s
a --|> s

usecase "See Course Progress" as UC1
usecase "Create Course Description" as UC2
usecase "Approve Created Courses" as UC3
usecase "Create Learning Steps" as UC4

usecase "Authenticate User" as auth

s -- UC1
t -- UC2
a -- UC3
t -- UC4

UC1 ..> auth : <<include>>
UC2 ..> auth : <<include>>
UC3 ..> auth : <<include>>
UC4 ..> auth : <<include>>

@enduml
