@startuml UseCaseDiagram
!include https://raw.githubusercontent.com/fredoslav2004/MinimalThemePUML/refs/heads/main/minimal-theme.puml

scale 1
left to right direction

actor "Learner" as s
package Internal {
    actor "Teacher" as t
    actor "Administrator" as a
}

t --|> s
a --|> s

package System {
    usecase "Register" as UC1
    usecase "Log in" as UC2
    usecase "Manage Personal Learning" as UC3
    usecase "Browse and Search Catalog" as UC4
    usecase "Complete Learning Step" as UC5
    usecase "View User Profile" as UC6
    usecase "View Leaderboard" as UC7
    usecase "Create Course Draft" as UC8
    usecase "Edit Course Content" as UC9
    usecase "Manage System Metadata" as UC10
    usecase "Review Course Drafts" as UC11
    usecase "Manage User Roles" as UC12
}


s -- UC1
s -- UC2
s -- UC3
s -- UC4
s -- UC5
s -- UC6
s -- UC7
t -- UC8
t -- UC9
a -- UC10
a-- UC11
a -- UC12

' Description of the diagram
footer all use cases include user authentication

@enduml
